export const siteContent = {
  hero: {
    title: "Julio Cabos",
    subtitle: "Pintura de miniaturas con criterio artístico",
    description:
      "Más de dos décadas dedicado a la pintura, la formación y la búsqueda de un estándar artístico en cada pieza.",
    cta: "Aprender conmigo",
    ctaHref: "#formacion",
    backgroundImage: "/images/hero.webp",
  },
  message: {
    text: [
      "La pintura de miniaturas no es solo técnica.",
      "Es entender la luz, el volumen y las decisiones que hacen que una figura funcione.",
      "",
      "Este es un espacio para aprender a pintar con criterio.",
    ],
  },
  training: {
    title: "Formación",
    text: "Formación presencial y online para todos los niveles. Un enfoque basado en entender la pintura, no solo ejecutarla.",
    primaryCta: "Cursos presenciales",
    primaryHref: "#contacto",
    secondaryCta: "Próximamente online",
    secondaryHref: "#",
  },
  about: {
    title: "Sobre Julio",
    image: "/images/about.webp",
    text: [
      "Julio Cabos es un pintor profesional de miniaturas con más de dos décadas de experiencia en el sector.",
      "Ha sido director de pintura en empresas de referencia como Andrea Miniatures y Scale75, liderando proyectos para coleccionistas y desarrollando publicaciones especializadas.",
      "Autor de más de 30 libros y formador internacional, combina su trabajo como pintor freelance con la enseñanza, ayudando a otros a entender la pintura desde el criterio y la experiencia.",
    ],
    cta: "Ver trayectoria",
    ctaHref: "/files/CV%20Funcional%20Julio.pdf",
  },
  contact: {
    title: "Contacto",
    text: "Si quieres aprender con Julio o colaborar en algún proyecto, puedes ponerte en contacto aquí.",
    email: "Juliocabosg@gmail.com",
    cta: "Enviar email",
  },
  footer: {
    name: "Julio Cabos",
    instagram: "https://www.instagram.com/juliocabos",
    facebook: "https://www.facebook.com/julio.cabos",
  },
};

export const galleryImages = [
  { src: "/images/gallery/samurai.webp", alt: "Samurái — miniatura pintada por Julio Cabos" },
  { src: "/images/gallery/templario.webp", alt: "Templario — encargo de pintura" },
  { src: "/images/gallery/abanderado.webp", alt: "Abanderado — figura histórica" },
  { src: "/images/gallery/paracaidista.webp", alt: "Paracaidista — box art" },
  { src: "/images/gallery/soldado.webp", alt: "Soldado — box art" },
  { src: "/images/gallery/arquero.webp", alt: "Arquero — encargo de pintura" },
  { src: "/images/gallery/arabia.webp", alt: "Figura árabe — box art" },
  { src: "/images/gallery/lancero.webp", alt: "Lancero — figura histórica" },
  { src: "/images/gallery/samurai-2.webp", alt: "Samurái — detalle" },
  { src: "/images/gallery/samurai-3.webp", alt: "Samurái — detalle" },
  { src: "/images/gallery/samurai-4.webp", alt: "Samurái — detalle" },
  { src: "/images/gallery/samurai-5.webp", alt: "Samurái — detalle" },
  { src: "/images/gallery/templario-2.webp", alt: "Templario — detalle" },
  { src: "/images/gallery/templario-3.webp", alt: "Templario — detalle" },
  { src: "/images/gallery/templario-4.webp", alt: "Templario — detalle" },
  { src: "/images/gallery/templario-5.webp", alt: "Templario — detalle" },
  { src: "/images/gallery/templario-6.webp", alt: "Templario — detalle" },
  { src: "/images/gallery/templario-7.webp", alt: "Templario — detalle" },
  { src: "/images/gallery/templario-8.webp", alt: "Templario — detalle" },
  { src: "/images/gallery/arquero-2.webp", alt: "Arquero — detalle" },
  { src: "/images/gallery/arquero-3.webp", alt: "Arquero — detalle" },
  { src: "/images/gallery/arquero-4.webp", alt: "Arquero — detalle" },
  { src: "/images/gallery/soldado-2.webp", alt: "Soldado — detalle" },
  { src: "/images/gallery/soldado-3.webp", alt: "Soldado — detalle" },
  { src: "/images/gallery/soldado-4.webp", alt: "Soldado — detalle" },
  { src: "/images/gallery/arabia-2.webp", alt: "Figura árabe — detalle" },
  { src: "/images/gallery/paracaidista-2.webp", alt: "Paracaidista — detalle" },
  { src: "/images/gallery/paracaidista-3.webp", alt: "Paracaidista — detalle" },
  { src: "/images/gallery/paracaidista-4.webp", alt: "Paracaidista — detalle" },
  { src: "/images/gallery/paracaidista-5.webp", alt: "Paracaidista — detalle" },
  { src: "/images/gallery/lancero-2.webp", alt: "Lancero — detalle" },
  { src: "/images/gallery/mini-1.webp", alt: "Miniatura de colección" },
  { src: "/images/gallery/mini-2.webp", alt: "Miniatura de colección" },
];
